{% set version = "6.4.20221004.1225" %}
{% set git_commit = "67ba3930c1c3626880b1900ac8f07177a56e8452" %}

package:
  name: mantid
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: c71f96883f9e8af6948f5ebedcacf56e2d75d6e3d73384bea9500d30f8a49cd6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantid', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - boost {{ boost }}
    - eigen
    - gsl {{ gsl }}
    - h5py
    - hdf5 {{ hdf5 }}
    - jemalloc  # [unix]
    - jsoncpp
    - librdkafka
    - lib3mf  # [win]
    - muparser
    - nexus
    - numpy {{ numpy }}
    - occt {{ occt }}
    - python {{ python }}
    - poco
    - tbb-devel {{ tbb }}
    - zlib
    - pip
    - openssl {{ openssl }}
  run:
    - {{ pin_compatible("boost", max_pin="x.x") }}
    - {{ pin_compatible("gsl", max_pin="x.x") }}
    - h5py
    - {{ pin_compatible("hdf5", max_pin="x.x") }}
    - lib3mf  # [win]
    - nexus
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("occt", max_pin="x.x.x") }}
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - openssl {{ openssl }}
    - euphonic=0.6.*
    - toml

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.
  description: Mantid provides a framework that supports high-performance computing and visualisation of materials science data. To use the optional plotting sub package you must pip install matplotlib 3.1.3 to ensure correct compatibility.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
