{% set version = "6.5.20221110.1704" %}
{% set git_commit = "850bfc9fd350b84d666b344414c66fe68df8dda7" %}

package:
  name: mantiddocs
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 46ec52d22a45de9950121381a092ffc2afb6c1a212fb18293ebecc8505b1e185

build:
  noarch: generic
  number: 0
  ignore_run_exports_from:
      - {{ compiler('cxx') }}
      - python

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - python
    - setuptools {{ setuptools }}
    - sphinx {{ sphinx }}
    - sphinx_bootstrap_theme
    - mantidqt {{ version }}

# there are no run requirements as it's just pure html

test:
  files:
    - share/doc/index.html
    - share/doc/mantid.png

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: The QtHelp documentation for mantid

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
