{% set version = "6.5.20221025.1803" %}
{% set git_commit = "aeb61550a4f509c1ca5ca885811d3e10520a2079" %}

package:
  name: mantiddocs
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: d35ce280b32496866046a8c3392a0b146894977e77065887c325f30b7e26b7b0

build:
  noarch: generic
  number: 0
  ignore_run_exports_from:
      - {{ compiler('cxx') }}
      - python

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - python
    - setuptools {{ setuptools }}
    - sphinx {{ sphinx }}
    - sphinx_bootstrap_theme
    - mantidqt {{ version }}

# there are no run requirements as it's just pure html

test:
  files:
    - share/doc/index.html
    - share/doc/mantid.png

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: The QtHelp documentation for mantid

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
