{% set version = "6.2.20220113.2323" %}
{% set git_rev = "827a94d1563cb2f20e8c0fd78cb037d034d95126" %}

package:
  name: mantid-workbench
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    # See http://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=libgl#libgl
    # and https://github.com/conda-forge/freeglut-feedstock/blob/master/recipe/meta.yaml
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]

  host:
    - boost {{ boost }} 
    - cmake
    - eigen
    - gsl
    - h5py
    - hdf4
    - hdf5
    - jsoncpp
    - libxcb
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy     {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - pyqt
    - python {{ python }}
    - qscintilla2
    - qt
    - qtawesome
    - qtconsole
    - qtpy
    - sphinx
    - sphinx_bootstrap_theme
    - tbb-devel

    # See http://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=libgl#libgl
    # and https://github.com/conda-forge/freeglut-feedstock/blob/master/recipe/meta.yaml
    - libglu
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxi                         # [linux]

  run:
    - boost {{ boost }} 
    - h5py
    - librdkafka
    - jsoncpp
    - nexus
    - numpy
    - openblas
    - poco
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb

about:
  home:
  license:
  license_file:
