{% set version = "6.4.20220811.1131" %}
{% set git_commit = "2ecc521f120f2131ca72ef572c965f2ecbd4c67b" %}

package:
  name: mantidqt
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: d905480f2b66a99858001bbc24b2c0d28775143ef925f6641fcf937533c25e9a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantidqt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - eigen
    - jemalloc  # [unix]
    - mantid {{ version }}
    - python
    - pyqt
    - qt {{ qt }}
    - qscintilla2
    - setuptools {{ setuptools }}
    - tbb-devel {{ tbb }}

  run:
    - matplotlib {{ matplotlib }}
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qtpy
    - python
    
test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - StephenSmith25
    - Pasarus