#!/bin/bash
# command for "build" section of jenkins "master_create_conda_linux_pkg" project

rm -rf conda-recipes
git clone https://github.com/mantidproject/conda-recipes
rsync -av conda-recipes/jenkins/Testing/ Testing/
./buildconfig/Jenkins/systemtests && \
    ANACONDA_ACCESS_KEY=$ANACONDA_ACCESS_KEY conda-recipes/jenkins/upload.sh -l nightly --force $(ls build/mantid-framework-*.tar.bz2)
