{% set version = "6.5.20221118.1339" %}
{% set git_commit = "814cf08723e4379857cb8985189bc166bd01dc5a" %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 9046b4257e4e96094ae30d8e6c535ee283bb1ee6b5ee82b2f373bc56eab83ed2

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true
  ignore_run_exports_from:
      - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - setuptools {{ setuptools }}
    - mantidqt {{ version }}
    - python
  run:
    - ipykernel {{ ipykernel }}
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - matplotlib {{ matplotlib }}
    - python.app  # [osx]
    - qtconsole
    - {{ pin_compatible("setuptools", max_pin="x.x") }}
    - mantiddocs {{ version }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: MantidWorkbench provides a graphical user interface to the Mantid framework, supporting high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
