{% set version = "6.4.20220920.0829" %}
{% set git_commit = "f1304350ea8d8dcaf02f1444ccd5eb06e8089b75" %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  url: https://github.com/mantidproject/mantid/archive/{{ git_commit }}.tar.gz
  sha256: 9b7f28b75a523d821b2d1deb2d72807f2cf506e2e33bd37bd01d729303a8768f

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true
  ignore_run_exports_from:
      - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - setuptools {{ setuptools }}
    - mantidqt {{ version }}
    - python
  run:
    - ipykernel {{ ipykernel }}
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - matplotlib {{ matplotlib }}
    - python.app  # [osx]
    - qtconsole
    - {{ pin_compatible("setuptools", max_pin="x.x") }}
    - mantiddocs {{ version }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: MantidWorkbench provides a graphical user interface to the Mantid framework, supporting high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
